apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-veqttmcs 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures, attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment.   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used tssc-gitops as the grouping
    argocd/app-selector: tssc/gitops=go-veqttmcs
    backstage.io/kubernetes-id: go-veqttmcs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: go-veqttmcs
    quay.io/repository-slug: rhtap_qe/go-veqttmcs
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 